## this file is used by a main script that will generate a new _config.yml file in each book at time of production.

title: "ROOT"
author: "Silvia Mazzoni"
copyright: "2026"
logo: './shared/images/common/logo.png'

only_build_toc_files: true

execute:
  execute_notebooks: "off"

sphinx:
  config:
    suppress_warnings: [myst.header]
    html_baseurl: "https://<YOURUSER>.github.io/<YOURREPO>/"
    html_copy_source: true
    html_favicon: "./shared/images/common/favicon_528227ad5610_ops.ico"
    source_suffix:
      .md: myst-nb
      .ipynb: myst-nb
    html_theme_options:
      show_navbar_depth: 1


launch_buttons:
  notebook_interface: "jupyterlab"
  thebe: true

repository:
  url: https://github.com/<YOURUSER>/<YOURREPO>
  branch: main

html:
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
  use_download_button: true
  logo: "./shared/images/common/logo.png"
  extra_static_paths:
    - _static
    - "./shared/_static"
  extra_css:
    - custom.css
  extra_js:
    - custom.js
  home_page_in_toc: true

parse:
  myst_enable_extensions:
    - html_admonition
    - html_image
    - colon_fence
  nb_remove_input_tags: ["remove-input"]
  nb_remove_cell_tags: ["remove-cell"]
  nb_remove_all_outputs_tags: ["remove-output"]
